export default {
  adjetivo: {
    a: 'adorável',
    b: 'bomdoso',
    c: 'carinhoso',
    d: 'divertido',
    e: 'esquisito',
    f: 'fantástico',
    g: 'gentil',
    h: 'humilde',
    i: 'inteligente',
    j: 'justa',
    k: '-',
    l: 'lindo',
    m: 'maravilhoso',
    n: 'linda',
    o: 'otimista',
    p: 'pequeno',
    q: 'quieto',
    r: 'rápido',
    s: 'simpático',
    t: 'teimoso',
    u: 'única',
    v: 'valente',
    w: 'workaholic',
    x: 'xexelenta',
    y: '-',
    z: 'zelosa',
  },
  animal: {
    a: 'anta',
    b: 'baleia',
    c: 'cachorro',
    d: 'dromedário',
    e: 'elefante',
    f: 'foca',
    g: 'girafa',
    h: 'hipopótamo',
    i: 'iguana',
    j: 'jaguatirica',
    k: '-',
    l: 'leão',
    m: 'mico leão dourado',
    n: 'naja',
    o: 'ovelha',
    p: 'pinguim',
    q: 'quero quero',
    r: 'rato',
    s: 'sapo',
    t: 'tatu',
    u: 'urubu',
    v: 'vaca',
    w: '-',
    x: '-',
    y: '-',
    z: 'zebra',
  },
  'app ou site': {
    a: 'amanco',
    b: 'bitbucket',
    c: 'casas bahia',
    d: '-',
    e: 'ebay',
    f: '-',
    g: 'google',
    h: '-',
    i: 'instagram',
    j: '-',
    k: '-',
    l: 'linkedin',
    m: 'magazine luiza',
    n: 'netflix',
    o: 'omeagle',
    p: 'pinterest',
    q: '-',
    r: '-',
    s: '-',
    t: 'telegram',
    u: '-',
    v: '-',
    w: 'whatsapp web',
    x: '-',
    y: 'youtube',
    z: 'zoom',
  },
  ator: {
    a: 'anita',
    b: 'brad pitt',
    c: 'cláudia raia',
    d: 'dede santana',
    e: 'emilio pitta',
    f: 'fabio assuncao',
    g: 'gloria pires',
    h: 'helena ranaldi',
    i: 'inez viegas',
    j: 'jo soares',
    k: 'kadu molterno',
    l: 'lua blanco',
    m: 'marcos frota',
    n: 'nair bello',
    o: 'olivia ortiz',
    p: 'paolla oliveira',
    q: 'quimbe',
    r: 'raul cortez',
    s: 'susana vieira',
    t: 'tais araujo',
    u: 'umberto magnami',
    v: 'vera fischer',
    w: 'wagner moura',
    x: 'xuxa lopes',
    y: 'yolanda cardoso',
    z: 'zacarias',
  },
  banda: {
    a: 'agridoce',
    b: 'barao vermelho',
    c: 'capital inicial',
    d: 'detonautas',
    e: 'engenheiros do hawaii',
    f: 'fake number',
    g: 'garotos de rua',
    h: 'hangar',
    i: 'imagine dragons',
    j: 'jota quest',
    k: 'kid vinil',
    l: 'legiao urbana',
    m: 'marron 5',
    n: 'nando reis',
    o: 'os paralamas',
    p: 'pavilhao 9',
    q: '-',
    r: 'raimundos',
    s: 'skank',
    t: 'tnt',
    u: 'utopia',
    v: 'vanguarda',
    w: 'wilson sideral',
    x: '-',
    y: 'yahoo',
    z: 'zero',
  },
  brinquedo: {
    a: 'arminha de água',
    b: 'bola',
    c: 'carrinho',
    d: 'dado',
    e: 'estilingue',
    f: 'fidget spinner',
    g: 'gira gira',
    h: 'hello kitty',
    i: 'ioio',
    j: 'jogo da vida',
    k: '-',
    l: 'lego',
    m: 'madballs',
    n: 'neocube',
    o: '-',
    p: 'pipa',
    q: '-',
    r: 'revell',
    s: 'soldado de brinquedo',
    t: 'trator',
    u: '-',
    v: '-',
    w: '-',
    x: '-',
    y: '-',
    z: 'zubbles',
  },
  cantor: {
    a: 'adele',
    b: 'beyounce',
    c: 'cesar mc',
    d: 'drake',
    e: 'eminem',
    f: 'foo figthers',
    g: 'guns n roses',
    h: 'henrique e juliano',
    i: 'iron maden',
    j: 'jorge e matheus',
    k: 'katy perry',
    l: 'lady gaga',
    m: 'matheus e kauan',
    n: 'naiara azevedo',
    o: 'one direction',
    p: 'pink',
    q: 'queen',
    r: 'roberto carlos',
    s: 'shakira',
    t: 'the beatles',
    u: 'u2',
    v: 'vitão',
    w: 'wiz khalifa',
    x: 'xama',
    y: 'yes',
    z: 'zeze dicamargo',
  },
  capital: {
    a: 'amsterda',
    b: 'brasília',
    c: '-',
    d: 'dublin',
    e: '-',
    f: '-',
    g: 'guatemala',
    h: '-',
    i: '-',
    j: 'jerusalem',
    k: '-',
    l: 'luxemburgo',
    m: 'moscou',
    n: '-',
    o: '-',
    p: 'panamá',
    q: 'quito',
    r: '-',
    s: 'sao paulo',
    t: 'toquio',
    u: '-',
    v: 'vitoria',
    w: 'washington',
    x: '-',
    y: '-',
    z: '-',
  },
  celebridade: {
    a: 'adele',
    b: 'beyounce',
    c: 'cesar mc',
    d: 'drake',
    e: 'eminem',
    f: 'foo figthers',
    g: 'guns n roses',
    h: 'henrique e juliano',
    i: 'iron maden',
    j: 'jorge e matheus',
    k: 'katy perry',
    l: 'lady gaga',
    m: 'matheus e kauan',
    n: 'nirvana',
    o: 'one direction',
    p: 'pink',
    q: 'queen',
    r: 'roberto carlos',
    s: 'shakira',
    t: 'the beatles',
    u: 'u2',
    v: 'vitão',
    w: 'wiz khalifa',
    x: 'xama',
    y: 'yes',
    z: 'zeze dicamargo',
  },
  cep: {
    a: 'amapá',
    b: 'brasília',
    c: 'ceará',
    d: 'divinópolis',
    e: 'espanha',
    f: 'franca',
    g: 'goias',
    h: '-',
    i: 'irlanda',
    j: 'jeceaba',
    k: '-',
    l: 'lisboa',
    m: 'maceió',
    n: 'natal',
    o: 'ouro preto',
    p: 'portugal',
    q: '-',
    r: 'roma',
    s: 'são paulo',
    t: 'tailandia',
    u: 'uruguai',
    v: 'venezuela',
    w: '-',
    x: '-',
    y: '-',
    z: 'zimbabue',
  },
  cidade: {
    a: 'anapolis',
    b: 'betim',
    c: 'capixaba',
    d: 'dourado',
    e: 'eldorado',
    f: 'floresta',
    g: 'goiania',
    h: 'horizonte',
    i: 'ibirité',
    j: 'jeceaba',
    k: 'kalore',
    l: 'lagoinha',
    m: 'macapa',
    n: 'natal',
    o: 'oliveira',
    p: 'palma',
    q: 'quilombo',
    r: 'raposa',
    s: 'sampaio',
    t: 'taubate',
    u: 'uberlandia',
    v: 'valenca',
    w: 'wall ferraz',
    x: 'xangrila',
    y: '-',
    z: 'ze doca',
  },
  'comida saudável': {
    a: 'alface',
    b: 'batata doce',
    c: 'castanha do para',
    d: 'damasco',
    e: 'espinafre',
    f: 'frango',
    g: 'gengibre',
    h: 'hibisco',
    i: 'integrais',
    j: 'jilo',
    k: 'kiwi',
    l: 'leite',
    m: 'maionese',
    n: 'nozes',
    o: 'ovo',
    p: 'peixe',
    q: 'quiabo',
    r: 'rucula',
    s: 'salada',
    t: 'tomate',
    u: 'uva',
    v: 'vitamina',
    w: '-',
    x: '-',
    y: '-',
    z: 'zinco',
  },
  cor: {
    a: 'azul marinho',
    b: 'branco',
    c: 'ciano',
    d: 'dourado',
    e: 'esmeralda',
    f: 'ferrugem',
    g: 'gelo',
    h: '-',
    i: 'indigo',
    j: 'jade',
    k: '-',
    l: 'lima',
    m: 'marrom',
    n: 'negro',
    o: 'ouro',
    p: 'preto',
    q: '-',
    r: 'roxo',
    s: 'salmao',
    t: 'turquesa',
    u: 'uva',
    v: 'verde escuro',
    w: '-',
    x: '-',
    y: '-',
    z: 'zaffre',
  },
  'desenho animado': {
    a: 'alvin e os esquilos',
    b: 'ben 10',
    c: 'capitao caverna',
    d: 'digimon',
    e: 'esquadrilha parafuso',
    f: 'futurama',
    g: 'galinha pintadinha',
    h: 'he man',
    i: 'inspetor bugiganga',
    j: 'jambo e ruivão',
    k: '-',
    l: 'liga da justica',
    m: 'megaman',
    n: 'naruto',
    o: 'one piece',
    p: 'pica pau',
    q: 'quarteto fantastico',
    r: 'riquinho',
    s: 'scooby doo',
    t: 'timao e pumba',
    u: 'universo blaster',
    v: 'voltron',
    w: 'will e dwiit',
    x: 'x men',
    y: 'yu gi oh',
    z: 'ze colmeia',
  },
  doce: {
    a: 'arroz doce',
    b: 'brigadeiro',
    c: 'churros',
    d: 'donuts',
    e: 'enroladinho doce',
    f: 'folheado',
    g: 'gelatina',
    h: 'hojaldras',
    i: 'iogurte',
    j: 'jurupinga com morango',
    k: 'kolache',
    l: 'leite condensado',
    m: 'mousse',
    n: 'nutella',
    o: 'ovomaltine',
    p: 'pudim',
    q: 'quindim',
    r: 'rocambole',
    s: 'sundae',
    t: 'torta',
    u: 'ustipci',
    v: 'victoria sandwich',
    w: 'waffle',
    x: 'xango',
    y: 'yemita de huevo',
    z: 'zeppole',
  },
  'eletro eletrônico': {
    a: 'amplificador',
    b: 'batedeira',
    c: 'celular',
    d: 'dvd',
    e: 'equalizador',
    f: 'fone de ouvido',
    g: 'gps',
    h: 'home pod',
    i: 'ipod',
    j: 'jukebox',
    k: 'kindle',
    l: 'lanterna',
    m: 'monitor',
    n: 'noteebook',
    o: 'oculos 3d',
    p: 'projetor',
    q: '-',
    r: 'roteador',
    s: 'ssd',
    t: 'tablet',
    u: 'ultrabook',
    v: 'videogame',
    w: 'webcam',
    x: 'xbox',
    y: '-',
    z: '-',
  },
  esportista: {
    a: 'aubameyang',
    b: 'bale',
    c: 'cristiano ronaldo',
    d: 'daniel alves',
    e: 'eden hazard',
    f: 'falcao garcia',
    g: 'gabriel jesus',
    h: 'harry kane',
    i: 'isco',
    j: 'julian draxler',
    k: 'kante',
    l: 'lewandowski',
    m: 'messi',
    n: 'neymar',
    o: 'ozil',
    p: 'philippe coutinho',
    q: 'quaresma',
    r: 'rabiot',
    s: 'suarez',
    t: 'thiago melo',
    u: 'umtiti',
    v: 'verrati',
    w: 'william',
    x: 'xhaka',
    y: 'yaya toure',
    z: 'zidane',
  },
  fantasia: {
    a: 'animal',
    b: 'banana',
    c: 'cavalo',
    d: 'dromedario',
    e: 'elefante',
    f: 'foca',
    g: 'gato',
    h: 'hipopotamo',
    i: 'iguana',
    j: 'jumento',
    k: 'kpop',
    l: 'lagarto',
    m: 'morcego',
    n: '-',
    o: 'ogro',
    p: 'passaro',
    q: '-',
    r: 'rato',
    s: 'sapo',
    t: 'tatu',
    u: 'urubu',
    v: 'vaca',
    w: '-',
    x: '-',
    y: '-',
    z: 'zorro',
  },
  filme: {
    a: 'alvin e os esquilos',
    b: 'burlesque',
    c: 'campo rock',
    d: 'divertidamente',
    e: 'ela danca eu danco',
    f: 'frida',
    g: 'ghost',
    h: 'higth school music',
    i: 'invocacao do mal',
    j: 'jumanji',
    k: 'kung fu panda',
    l: 'livrainos do mal',
    m: 'minha mae e uma peca',
    n: 'nerve',
    o: 'os incriveis',
    p: 'procurando nemo',
    q: 'quando as luzes se apagam',
    r: 'rio',
    s: 'sex and city',
    t: 'titanic',
    u: 'uma linda mulher',
    v: 'viva',
    w: 'wall e',
    x: 'xuxa',
    y: 'yu gi oh',
    z: 'zumbilandia',
  },
  flor: {
    a: 'acafrao',
    b: 'beijo de moca',
    c: 'cravo',
    d: 'dalia',
    e: 'erva mate',
    f: 'flor de lotus',
    g: 'girassol',
    h: 'hibisco',
    i: 'iris',
    j: 'jasmin',
    k: 'kaizuka',
    l: 'lirio',
    m: 'margarida',
    n: 'narciso',
    o: 'orquidea',
    p: 'petunia',
    q: 'quaresmeira',
    r: 'rosa',
    s: 'salvia',
    t: 'tulipa',
    u: 'unha de gato',
    v: 'violeta',
    w: 'washingtonia',
    x: 'xantorreia',
    y: 'yuca',
    z: 'zinias',
  },
  fruta: {
    a: 'abacaxi',
    b: 'banana',
    c: 'caju',
    d: 'damasco',
    e: 'embauba',
    f: 'figo',
    g: 'goiaba',
    h: 'heinsteria',
    i: 'inga',
    j: 'jabuticaba',
    k: 'kiwi',
    l: 'laranja',
    m: 'mamao',
    n: 'noz',
    o: 'olho de boi',
    p: 'pera',
    q: 'quina',
    r: 'roma',
    s: 'sapucaia',
    t: 'tamarindo',
    u: 'uva',
    v: 'veludo',
    w: '-',
    x: 'xixa',
    y: 'yamamomo',
    z: 'zimbro',
  },
  game: {
    a: 'angry birds',
    b: 'batman',
    c: 'cars',
    d: 'darksiders',
    e: 'echo nigth',
    f: 'fifa',
    g: 'god of war',
    h: 'half life',
    i: 'imperium',
    j: 'just dance',
    k: '-',
    l: 'league of legends',
    m: 'mega man',
    n: 'ninja blade',
    o: 'outlander',
    p: 'pacman',
    q: 'quick step',
    r: 'resident evil',
    s: 'silent hill',
    t: 'tomb raider',
    u: 'ultimate casino',
    v: 'vortex',
    w: '-',
    x: 'x men',
    y: '-',
    z: 'zoop',
  },
  gentílico: {
    a: 'africano',
    b: 'baiano',
    c: 'carioca',
    d: 'dinamarques',
    e: 'espanhol',
    f: 'frances',
    g: 'goiano',
    h: 'havaiano',
    i: 'indiano',
    j: 'jamaicano',
    k: 'kosovar',
    l: 'lagoense',
    m: 'mineiro',
    n: 'noruegues',
    o: 'oceanico',
    p: 'portugues',
    q: 'queniano',
    r: 'romano',
    s: 'servio',
    t: 'turco',
    u: 'uruguaio',
    v: 'venezuelano',
    w: 'whashingtoniano',
    x: 'xangaies',
    y: 'yorkshiriano',
    z: 'zimbabuano',
  },
  idioma: {
    a: 'arabe',
    b: 'bosnio',
    c: 'chines',
    d: 'dinamarques',
    e: 'espanhol',
    f: 'frances',
    g: 'grego',
    h: 'hungaro',
    i: 'ingles',
    j: 'japones',
    k: 'karana',
    l: 'latim',
    m: 'mongol',
    n: 'noruegues',
    o: 'oria',
    p: 'portugues',
    q: 'quinchua',
    r: 'russo',
    s: 'servio',
    t: 'turco',
    u: 'ucraniano',
    v: 'vietnamita',
    w: '-',
    x: 'xhosa',
    y: '-',
    z: 'zulu',
  },
  inseto: {
    a: 'abelha',
    b: 'besouro',
    c: 'cupim',
    d: '-',
    e: 'entomologia',
    f: 'formiga',
    g: 'grilo',
    h: '-',
    i: '-',
    j: 'joaninha',
    k: '-',
    l: '-',
    m: 'mosca',
    n: '-',
    o: '-',
    p: 'percevejo',
    q: '-',
    r: '-',
    s: 'salamantra',
    t: '-',
    u: '-',
    v: 'vespa',
    w: '-',
    x: '-',
    y: '-',
    z: 'zangao',
  },
  jlr: {
    a: '-',
    b: '-',
    c: '-',
    d: '-',
    e: '-',
    f: '-',
    g: '-',
    h: '-',
    i: '-',
    j: '-',
    k: '-',
    l: '-',
    m: '-',
    n: '-',
    o: '-',
    p: '-',
    q: '-',
    r: '-',
    s: '-',
    t: '-',
    u: '-',
    v: '-',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  líquido: {
    a: 'agua',
    b: 'bebida',
    c: 'coca cola',
    d: '',
    e: '-',
    f: 'fanta',
    g: 'guarana',
    h: '-',
    i: 'iacute',
    j: '-',
    k: '-',
    l: '-',
    m: 'mamadeira',
    n: 'nescau',
    o: '-',
    p: '-',
    q: '-',
    r: 'rum',
    s: 'suco',
    t: 'toddy',
    u: 'urina',
    v: 'vitamina',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  mamífero: {
    a: 'anta',
    b: 'baleia',
    c: 'cabra',
    d: 'dromedario',
    e: 'egua',
    f: 'furao',
    g: 'girafa',
    h: 'hamster',
    i: 'impala',
    j: 'javali',
    k: 'kudu',
    l: 'leao',
    m: 'macaco',
    n: 'narval',
    o: 'onca',
    p: 'pato',
    q: 'quati',
    r: 'raposa',
    s: 'sagui',
    t: 'tatu',
    u: 'urso',
    v: 'vaca',
    w: '-',
    x: '-',
    y: '-',
    z: 'zebra',
  },
  marca: {
    a: 'adidas',
    b: 'blue bird',
    c: 'canon',
    d: 'dell',
    e: 'epson',
    f: 'feber',
    g: 'go pro',
    h: 'hp',
    i: 'iphone',
    j: 'jbl',
    k: 'kingstom',
    l: 'lenovo',
    m: 'microsoft',
    n: 'nintendo',
    o: 'olympus',
    p: 'philips',
    q: '-',
    r: 'razer',
    s: 'samsumg',
    t: 'taurus',
    u: 'ufessa',
    v: 'vanguard',
    w: 'wizard',
    x: 'xerox',
    y: 'yamaha',
    z: 'zanussi',
  },
  'meio de transporte': {
    a: 'aviao',
    b: 'bicicleta',
    c: 'carro',
    d: 'drone',
    e: 'elevador',
    f: 'foguete',
    g: 'guincho',
    h: 'helicoptero',
    i: 'iate',
    j: 'jet ski',
    k: 'kite surf',
    l: 'lancha',
    m: 'moto',
    n: 'navio',
    o: 'onibus',
    p: 'prancha',
    q: 'quadriciculo',
    r: 'retroscavadeira',
    s: 'skate',
    t: 'trem',
    u: 'uber',
    v: 'vagao',
    w: 'wind surf',
    x: 'xebec',
    y: 'yawl',
    z: 'zepplin',
  },
  música: {
    a: 'animal',
    b: 'bedtime story',
    c: 'cant stop',
    d: 'doing me',
    e: 'everithing of me',
    f: 'fan mail',
    g: 'game of life',
    h: 'hey az',
    i: 'i am the truth',
    j: 'just because',
    k: '-',
    l: 'let me know',
    m: 'make me',
    n: 'never change',
    o: 'once again',
    p: 'paradise',
    q: 'quiet money',
    r: 'rock me',
    s: 'serious',
    t: 'take it off',
    u: 'uncut raw',
    v: 'vandetta',
    w: 'wanna be there',
    x: '-',
    y: 'your world dont stop',
    z: '-',
  },
  nome: {
    a: 'amanda',
    b: 'bianca',
    c: 'carla',
    d: 'diana',
    e: 'ester',
    f: 'fatima',
    g: 'gabriela',
    h: 'higor',
    i: 'ivone',
    j: 'jorge',
    k: 'kiara',
    l: 'larissa',
    m: 'maisa',
    n: 'nathan',
    o: 'osvaldo',
    p: 'pericles',
    q: 'qeren',
    r: 'raphael',
    s: 'sabrina',
    t: 'tiago',
    u: 'umberto',
    v: 'vitor',
    w: 'william',
    x: 'xuxa',
    y: 'yago',
    z: 'zeze',
  },
  'nome feminino': {
    a: 'aline',
    b: 'bruna',
    c: 'carla',
    d: 'daniela',
    e: 'ester',
    f: 'fatima',
    g: 'gariela',
    h: '-',
    i: 'ivone',
    j: 'jaqueline',
    k: '-',
    l: 'leticia',
    m: 'marcela',
    n: 'natalia',
    o: 'olivia',
    p: 'patricia',
    q: 'queren',
    r: 'rafaela',
    s: 'sabrina',
    t: 'tatiana',
    u: '-',
    v: 'vitoria',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  'nome masculino': {
    a: 'arthur',
    b: 'bruno',
    c: 'carlos',
    d: 'diego',
    e: 'emerson',
    f: 'fabio',
    g: 'gabriel',
    h: 'hugo',
    i: 'iago',
    j: 'jhonatan',
    k: 'kaique',
    l: 'leandro',
    m: 'matheus',
    n: 'nathan',
    o: 'osvaldo',
    p: 'pedro',
    q: '-',
    r: 'raphael',
    s: 'sabrina',
    t: 'thiago',
    u: 'umberto',
    v: 'vitor',
    w: 'william',
    x: 'xico',
    y: 'yago',
    z: '-',
  },
  objeto: {
    a: 'alcapao',
    b: 'bola',
    c: 'corda',
    d: 'dado',
    e: 'estante',
    f: 'faca',
    g: 'gaveta',
    h: '-',
    i: 'iluminaria',
    j: 'jbl',
    k: '-',
    l: '-',
    m: 'maquina de escrever',
    n: '-',
    o: 'oculos',
    p: 'pipa',
    q: '-',
    r: 'ratoeira',
    s: 'sapato',
    t: 'tenis',
    u: 'ukulele',
    v: 'violao',
    w: '-',
    x: '-',
    y: '-',
    z: 'ziper',
  },
  'palavra em espanhol': {
    a: 'abeja',
    b: 'banera',
    c: 'caballo',
    d: 'dedo',
    e: 'estrella',
    f: 'falda',
    g: 'gancho',
    h: 'hola',
    i: 'isla',
    j: 'joya',
    k: '-',
    l: 'luna',
    m: 'martillo',
    n: 'nudo',
    o: 'ojo',
    p: 'pajaro',
    q: 'queso',
    r: 'rueda',
    s: 'sello',
    t: 'tabla',
    u: '-',
    v: 'vaca',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  'palavra em inglês': {
    a: 'all',
    b: 'become',
    c: 'car',
    d: 'dead',
    e: 'end',
    f: 'fight',
    g: 'german',
    h: 'human',
    i: 'invisible',
    j: 'jacket',
    k: 'kart',
    l: 'lemon',
    m: 'mother',
    n: 'never',
    o: 'old',
    p: 'park',
    q: '-',
    r: 'rock',
    s: 'smile',
    t: 'test',
    u: 'undo',
    v: 'very',
    w: 'wash',
    x: 'xbow',
    y: 'yes',
    z: 'zoom',
  },
  país: {
    a: 'alemanha',
    b: 'brasil',
    c: 'chile',
    d: 'dinamarca',
    e: 'espanha',
    f: 'franca',
    g: 'grecia',
    h: 'holanda',
    i: 'india',
    j: 'jamaica',
    k: 'kosovo',
    l: 'londres',
    m: 'malasia',
    n: 'nepal',
    o: 'oma',
    p: 'portugal',
    q: 'qatar',
    r: 'roma',
    s: 'suica',
    t: 'tailandia',
    u: 'ucrania',
    v: 'vaticano',
    w: '-',
    x: '-',
    y: '-',
    z: 'zimbabue',
  },
  pch: {
    a: 'ant braco',
    b: 'braco',
    c: 'cabeca',
    d: 'dente',
    e: 'estomago',
    f: 'faringe',
    g: 'garganta',
    h: '-',
    i: 'iris',
    j: 'joelho',
    k: '-',
    l: 'lingua',
    m: 'mao',
    n: '-',
    o: 'orelha',
    p: 'perna',
    q: 'queixo',
    r: '-',
    s: 'sombrancelha',
    t: 'tornozelo',
    u: 'unha',
    v: 'vagina',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  pda: {
    a: 'alvin',
    b: 'ben 10',
    c: 'cascao',
    d: 'dick vigarista',
    e: '-',
    f: 'frajola',
    g: 'gaara',
    h: 'he man',
    i: 'itachi uchiha',
    j: 'jubileu',
    k: '-',
    l: 'leoncio',
    m: 'magneto',
    n: 'naruto',
    o: 'olivia palito',
    p: 'papa leguas',
    q: 'quindim',
    r: 'raphael tartarugas',
    s: 'sakura',
    t: 'tempestade',
    u: 'ursinho puf',
    v: 'vampira',
    w: 'wilma flingston',
    x: 'xman',
    y: 'yu gi oh',
    z: 'zeca urubu',
  },
  'personagem fictício': {
    a: 'alvin',
    b: 'ben 10',
    c: 'cascao',
    d: 'dick vigarista',
    e: '-',
    f: 'frajola',
    g: 'gaara',
    h: 'he man',
    i: 'itachi uchiha',
    j: 'jubileu',
    k: '-',
    l: 'leoncio',
    m: 'magneto',
    n: 'naruto',
    o: 'olivia palito',
    p: 'papa leguas',
    q: 'quindim',
    r: 'raphael tartarugas',
    s: 'sakura',
    t: 'tempestade',
    u: 'ursinho puf',
    v: 'vampira',
    w: 'wilma flingston',
    x: 'xman',
    y: 'yu gi oh',
    z: 'zeca urubu',
  },
  'programa de tv': {
    a: 'a fazenda',
    b: 'balanco geral',
    c: 'casos de familia',
    d: 'domingo espetacular',
    e: 'eliana',
    f: 'faustao',
    g: 'globo rural',
    h: 'hoje em dia',
    i: 'idolos',
    j: 'jo',
    k: '-',
    l: 'legendarios',
    m: 'malhacao',
    n: 'namoro na tv',
    o: 'o aprendiz',
    p: 'panico na band',
    q: 'quarta total',
    r: 'ratinho',
    s: 'show da fe',
    t: 'tv fama',
    u: 'ufc',
    v: 'vai que cola',
    w: '-',
    x: 'xuxa',
    y: '-',
    z: 'ze colmeia',
  },
  'raça de cachorro': {
    a: 'akita',
    b: 'buldog',
    c: 'chiuhaua',
    d: 'dalmata',
    e: '-',
    f: 'fox terrier',
    g: 'golden',
    h: 'husky',
    i: '-',
    j: 'jack russel',
    k: 'komondor',
    l: 'labrador',
    m: 'mastife',
    n: 'norwich',
    o: '-',
    p: 'pastor alemao',
    q: '-',
    r: 'rottweiler',
    s: 'skye',
    t: 'terrier',
    u: '-',
    v: 'vira lata',
    w: 'weimaraner',
    x: 'xoloitzcuitli',
    y: 'yorkshire',
    z: '-',
  },
  remédio: {
    a: 'acido folico',
    b: 'bezetacil',
    c: 'cloreto de sodio',
    d: 'dipirona',
    e: 'estriol',
    f: 'fluconazol',
    g: 'gliclazida',
    h: 'hidocloreto',
    i: 'ibuprofeno',
    j: '-',
    k: '-',
    l: 'loratadina',
    m: 'metiolate',
    n: 'nicotina',
    o: 'oleo mineral',
    p: 'paracetamol',
    q: '-',
    r: 'ritonavir',
    s: 'sulfato ferroso',
    t: 'tuberculina',
    u: '-',
    v: 'verapamil',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  'sabor de sorvete': {
    a: 'abacaxi',
    b: 'baunilha',
    c: 'chocolate branco',
    d: 'danone',
    e: '-',
    f: 'flocos',
    g: 'ganashi',
    h: '-',
    i: '-',
    j: 'jabuticaba',
    k: '-',
    l: 'limao',
    m: 'morango',
    n: 'napolitano',
    o: 'ovomaltine',
    p: 'pistache',
    q: '-',
    r: 'romeu e julieta',
    s: '-',
    t: 'tentacao',
    u: 'uva',
    v: 'vanila',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  sobrenome: {
    a: 'albuquerque',
    b: 'bernardes',
    c: 'cristiano',
    d: 'da silva',
    e: 'eller',
    f: 'fagundes',
    g: 'giovani',
    h: 'henrique',
    i: 'italo',
    j: 'jacinto',
    k: 'kiefer',
    l: 'leonardo',
    m: 'moraes',
    n: 'nicoli',
    o: 'oliveira',
    p: 'paes',
    q: 'quaresma',
    r: 'resende',
    s: 'sales',
    t: 'timoteo',
    u: 'uliana',
    v: 'vieira',
    w: 'walker',
    x: 'xavier',
    y: '-',
    z: 'zardo',
  },
  'super-herói': {
    a: 'arqueiro verde',
    b: 'batman',
    c: 'capitao america',
    d: 'demolidor',
    e: 'elektra',
    f: 'flash',
    g: 'green lantern',
    h: 'homen de ferro',
    i: 'iron man',
    j: 'justice',
    k: 'kick ass',
    l: 'lion',
    m: 'mulher maravilha',
    n: 'noturno',
    o: 'orion',
    p: 'punisher',
    q: 'quicksilver',
    r: '-',
    s: 'superman',
    t: 'thor',
    u: 'ultra boy',
    v: 'visao',
    w: 'wolverine',
    x: 'xavier',
    y: 'yu gi oh',
    z: 'zorro',
  },
  série: {
    a: 'a diarista',
    b: 'baby daddy',
    c: 'callifornication',
    d: 'dark blue',
    e: 'eu a patroa e as crian',
    f: 'friends',
    g: 'greys anatomy',
    h: 'house',
    i: 'invasion',
    j: 'joey',
    k: 'kyle xy',
    l: 'lie to me',
    m: 'moonlight',
    n: 'nip tuck',
    o: 'one three hill',
    p: 'prision break',
    q: '-',
    r: 'roma',
    s: 'simpsons',
    t: 'todo mundo odeia o cris',
    u: 'um maluco no pedaco',
    v: 'veronica mars',
    w: 'white collar',
    x: '-',
    y: '-',
    z: 'zorro',
  },
  'time esportivo': {
    a: 'ajax',
    b: 'barcelona',
    c: 'coritiba',
    d: 'democrata gv',
    e: 'everton',
    f: 'fiorentina',
    g: 'getafe',
    h: 'holanda',
    i: 'inter de milao',
    j: 'juventus',
    k: '-',
    l: 'lazio',
    m: 'mallorca',
    n: 'napoli',
    o: 'olimpia',
    p: 'palmeiras',
    q: 'queens park rangers',
    r: 'real madrid',
    s: 'sao paulo',
    t: 'taiti',
    u: 'uruguai',
    v: 'vasco',
    w: 'watford',
    x: 'xv de jau',
    y: 'ypiranga',
    z: 'zenit',
  },
  verbo: {
    a: 'amar',
    b: 'beijar',
    c: 'casar',
    d: 'dancar',
    e: 'entimidar',
    f: 'fazer',
    g: 'gostar',
    h: 'humilhar',
    i: 'imitar',
    j: 'jogar',
    k: '-',
    l: 'lancar',
    m: 'mostrar',
    n: 'nadar',
    o: 'olhar',
    p: 'pular',
    q: '-',
    r: 'roer',
    s: 'subir',
    t: 'trabalhar',
    u: 'uivar',
    v: 'vender',
    w: '-',
    x: '-',
    y: '-',
    z: 'zoar',
  },
  vestuário: {
    a: 'abotoadura',
    b: 'burca',
    c: 'casaco',
    d: 'decote',
    e: 'estampa',
    f: 'fivela',
    g: 'gola',
    h: 'havaiana',
    i: '-',
    j: 'jaqueta',
    k: '-',
    l: 'luva',
    m: 'meia',
    n: 'neglige',
    o: 'oculos',
    p: 'pijama',
    q: 'quimono',
    r: 'regata',
    s: 'sapato',
    t: 'toca',
    u: 'unha postica',
    v: '-',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  carro: {
    a: 'audi',
    b: 'bugati',
    c: 'corvete',
    d: 'ducati',
    e: 'estrada',
    f: 'ford',
    g: 'golf',
    h: 'hyundai',
    i: 'iveco',
    j: 'jaguar',
    k: 'kia',
    l: 'limosine',
    m: 'mercedes',
    n: 'nissan',
    o: '-',
    p: 'palio',
    q: '-',
    r: '-',
    s: 'subaru',
    t: 'toyota',
    u: 'uno',
    v: 'volkswagen',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  comida: {
    a: 'abacaxi',
    b: 'banana',
    c: 'cenoura',
    d: 'danone',
    e: '-',
    f: 'feijao',
    g: 'granola',
    h: '-',
    i: '-',
    j: 'jabuticaba',
    k: '-',
    l: 'limao',
    m: 'melancia',
    n: '-',
    o: 'oleo de oliva',
    p: 'pepino',
    q: '-',
    r: 'rabanada',
    s: 'strogonoff',
    t: 'torta',
    u: 'uva',
    v: 'vagem',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  'sabor de pizza': {
    a: 'alho e oleo',
    b: 'bacon',
    c: 'calabresa',
    d: 'doce de leite',
    e: 'espinafre',
    f: 'frango',
    g: 'gorgonzola',
    h: 'havaiana',
    i: '-',
    j: 'jardineira',
    k: '-',
    l: 'lombo',
    m: 'marguerita',
    n: 'napolitana',
    o: '-',
    p: 'palmito',
    q: 'queijo',
    r: 'romeu e julieta',
    s: 'salame',
    t: 'tomate',
    u: '-',
    v: 'vegetariana',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  esporte: {
    a: 'arco e flecha',
    b: 'boliche',
    c: 'ciclismo',
    d: 'dardos',
    e: 'esgrima',
    f: 'fsiculturismo',
    g: 'golfe',
    h: 'hipismo',
    i: 'iatismo',
    j: 'judo',
    k: 'karate',
    l: 'luta livre',
    m: 'mma',
    n: 'natacao',
    o: 'over the line',
    p: 'pilates',
    q: 'queimada',
    r: 'remo',
    s: 'surf',
    t: 'tiro ao alvo',
    u: 'ultramaratona',
    v: 'volei',
    w: 'widnsurf',
    x: 'xadrez',
    y: 'yoga',
    z: 'zumba',
  },
  vilão: {
    a: 'arlequina',
    b: 'bellatrix',
    c: 'coringa',
    d: 'death vader',
    e: 'esther',
    f: 'freddy krugger',
    g: 'galactus',
    h: 'hannibal',
    i: 'impiedosa',
    j: 'jason',
    k: 'korvac',
    l: 'loki',
    m: 'majin boo',
    n: 'norman',
    o: 'omega vermelho',
    p: 'pazuzu',
    q: 'quarteto terrivel',
    r: 'rainha vermelha',
    s: 'sauron',
    t: 'thanos',
    u: 'ultron',
    v: 'voldemort',
    w: '-',
    x: '-',
    y: '-',
    z: 'zorro',
  },
  'instrumento musical': {
    a: 'acordeom',
    b: 'baixo',
    c: 'cavaco',
    d: 'daxofone',
    e: 'eufonio',
    f: 'flauta',
    g: 'gaita',
    h: 'harpa',
    i: 'instrumento musical',
    j: '-',
    k: 'koto',
    l: 'lira',
    m: 'macara',
    n: '-',
    o: 'oboe',
    p: 'pandeiro',
    q: 'quissanje',
    r: 'reco reco',
    s: 'saxofone',
    t: 'tambor',
    u: 'ukulele',
    v: 'violino',
    w: '-',
    x: 'xeol',
    y: '-',
    z: '-',
  },
  presente: {
    a: '-',
    b: 'bateria',
    c: 'carro',
    d: 'danone',
    e: 'espinafre',
    f: 'faca',
    g: 'garrafa de vinho',
    h: '-',
    i: 'ima',
    j: 'jaula',
    k: '-',
    l: 'limonada',
    m: 'maca do amor',
    n: 'noz',
    o: 'oculos',
    p: 'pinjente',
    q: 'quiabo',
    r: 'ratoeira',
    s: 'sapato',
    t: 'tenis',
    u: 'uva',
    v: 'viagem',
    w: 'wolverine de brinquedo',
    x: 'xerox',
    y: 'yoyo',
    z: 'zarabatana',
  },
  ave: {
    a: 'arara',
    b: 'beija flor',
    c: 'canario',
    d: 'dancador',
    e: 'ema',
    f: 'falcao',
    g: 'gaivota',
    h: 'harpla',
    i: 'ibis',
    j: 'joao de barro',
    k: '-',
    l: 'limpa folha',
    m: 'macarico',
    n: 'noivinha',
    o: 'ogea',
    p: 'papa capim',
    q: 'quero quero',
    r: 'rolinha',
    s: 'sabia',
    t: 'tucano',
    u: 'urubu',
    v: 'vira folha',
    w: '-',
    x: 'xexeu',
    y: '-',
    z: 'zebele',
  },
  ingrediente: {
    a: 'abacaxi',
    b: 'banana',
    c: 'caju',
    d: 'damasco',
    e: 'espinafre',
    f: 'frango',
    g: 'goiaba',
    h: '-',
    i: '-',
    j: 'jilo',
    k: '-',
    l: 'limao',
    m: 'mamao',
    n: 'noz',
    o: 'ovo',
    p: 'pao de queijo',
    q: 'queijo',
    r: 'ricota',
    s: 'salame',
    t: 'taco',
    u: 'uva',
    v: 'vagem',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
  msé: {
    a: 'amavel',
    b: 'bonita',
    c: 'casada',
    d: 'doente',
    e: 'espetacular',
    f: 'folgada',
    g: 'gorda',
    h: 'humana',
    i: 'india',
    j: 'jumenta',
    k: 'kpoper',
    l: 'linda',
    m: 'maravilhosa',
    n: 'nanica',
    o: 'ostentacao',
    p: 'pequena',
    q: 'quieta',
    r: 'ruim',
    s: 'sentimental',
    t: 'triste',
    u: 'unica',
    v: 'valente',
    w: '-',
    x: 'xexelenta',
    y: '-',
    z: 'zoeira',
  },
  doença: {
    a: 'aids',
    b: 'botulismo',
    c: 'covid',
    d: 'dengue',
    e: 'ebola',
    f: 'febre amarela',
    g: 'gripe',
    h: 'hepatite',
    i: 'infeccao',
    j: '-',
    k: '-',
    l: 'leptospirose',
    m: 'malaria',
    n: 'novo coronavirus',
    o: 'oncocercose',
    p: 'pneumonia',
    q: 'qualifar',
    r: 'rubeola',
    s: 'sarampo',
    t: 'trombose',
    u: '-',
    v: 'varises',
    w: '-',
    x: '-',
    y: '-',
    z: 'zika virus',
  },
  profissão: {
    a: 'artesao',
    b: 'balconista',
    c: 'cantor',
    d: 'designer',
    e: 'ecologista',
    f: 'ferreiro',
    g: 'garcom',
    h: 'historiador',
    i: 'instrutor',
    j: 'jardineiro',
    k: '-',
    l: 'lutador',
    m: 'magico',
    n: 'narrador',
    o: 'odontologista',
    p: 'padeiro',
    q: 'quimico',
    r: 'radiologista',
    s: 'soldado',
    t: 'trocador',
    u: 'urologista',
    v: 'vereador',
    w: '-',
    x: 'xaropeiro',
    y: '-',
    z: 'zelador',
  },
  sobremesa: {
    a: 'arroz doce',
    b: 'brigadeiro',
    c: 'chocolate',
    d: 'donuts',
    e: 'empada',
    f: 'frango',
    g: 'gelatina',
    h: '-',
    i: '-',
    j: 'jabuticaba',
    k: '-',
    l: 'leite condensado',
    m: 'mousse',
    n: 'nutela',
    o: 'ovo',
    p: 'panqueca',
    q: 'queijo',
    r: 'rocambole',
    s: 'salada de frutas',
    t: 'torta',
    u: '-',
    v: 'vitamina',
    w: '-',
    x: '-',
    y: '-',
    z: '-',
  },
};
